//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleProject20200708.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        
        public int fId { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage ="姓名不可為空白")]
        public string fName { get; set; }
        [DisplayName("分數")]
        [Range(0,100,ErrorMessage = "分數必須為正整數0-100")]
        public Nullable<int> fScore { get; set; }
        [DisplayName("興趣")]
        [DataType(DataType.Text,ErrorMessage ="請輸入文字")] //[DataType(DataType.Text)]裡面的DataType是Enum，本身有許多Field，像是Date / Text / Password / Url ....
                                                             //用Datatype這個Enum列舉，選出需要的資料型態
        public string fHabit { get; set; }
        [DisplayName("學號")]
        [Required(ErrorMessage = "學號不可空白")]
        [Range(0,1000,ErrorMessage ="輸入0~1000內整數")]
        public Nullable<int> fStudentID { get; set; }
    }
}
